# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "sunrise"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Site Information
title: "JCSS Working Group on Uncertain Climate Futures"
description: "A scientific group website."
url: "https://daniwest.github.io" # Change to your actual URL
baseurl: "/JCSS_UncertainClimateFutures" # Keep this empty if your repo is [username].github.io
