# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "sunrise"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Site Information
title: "JCSS Working Group on Uncertain Climate Futures"
description: "A scientific group website."
url: "https://daniwest.github.io" # Change to your actual URL
baseurl: "/JCSS_UncertainClimateFutures" # Keep this empty if your repo is [username].github.io

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      header:
        title: "Managing Structures and Infrastructure for Uncertain Climate Futures"
        tagline: "Optimal strategies to handle climate uncertainty in civil infrastructure."
        overlay_image: https://daniwest.github.io//JCSS_UncertainClimateFutures/images/MountainDS.jpg
        overlay_filter: 0.2 # Makes text readable over an image
        caption: "Photo credit: Daniel Straub"
        actions:
          - label: "Motivation and case studies"
            url: "/cases/"
          - label: "Climate loads"
            url: "/loads/"
          - label: "Methods & tools"
            url: "/methods/"
          - label: "Resources"
            url: "/resources/"
          - label: "Members"
            url: "/members/"
